DROP TABLE IF EXISTS user_accounts;
DROP TABLE IF EXISTS assigned_users;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS task_statuses;
DROP TABLE IF EXISTS projects;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS accounts;
