// create a new account
http://localhost:8080
POST /account
{
	"name": "Test Account",
	"description": "This was created using the HTTP API"
}

// list accounts
http://localhost:8080
GET /account

// get an account
http://localhost:8080
GET /account/5f2d9a95-b335-493f-a7ed-8dbd81027bac

// create a new project
http://localhost:8080
POST /project
{
	"name": "Test Project",
	"description": "Just a test project",
	"accountId": "f6e9aa50-5071-484f-9390-066a80e80108"
}

// list projects
http://localhost:8080
GET /project

// list projects by account
http://localhost:8080
GET /project?accountId=5f2d9a95-b335-493f-a7ed-8dbd81027bac

// get a project
http://localhost:8080
GET /project/93305d12-6186-4002-a180-1d93ea9f74cb

// get a token
http://localhost:8080
GET /token/d163193e-6f6a-4a71-92a1-c76d3148559a
